name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_pxjmIbrbEY7prXDWAYACNVQV
          VERCEL_PROJECT_ID: prj_yHLRAp63hcau5D8OTB4oxNyCIIlq
